[project]
name = "python-project-templates"
readme = "README.md"
license = { text = "Apache-2.0" }
version = "0.1.0"
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
develop = [
    "copier",
]
