CARGO_NEXTEST_VERSION ?= 0.9.140
CARGO_LLVM_COV_VERSION ?= 0.8.7
WASM_BINDGEN_CLI_VERSION ?= 0.2.126

.PHONY: requirements develop build
requirements:  ## install required dev dependencies
	rustup component add rustfmt
	rustup component add clippy
	command -v cargo-nextest >/dev/null 2>&1 || cargo install --locked cargo-nextest --version =$(CARGO_NEXTEST_VERSION)
	command -v cargo-llvm-cov >/dev/null 2>&1 || cargo install --locked cargo-llvm-cov --version =$(CARGO_LLVM_COV_VERSION)
	command -v wasm-bindgen >/dev/null 2>&1 || cargo install --locked wasm-bindgen-cli --version =$(WASM_BINDGEN_CLI_VERSION)
	rustup target add wasm32-unknown-unknown

develop: requirements  ## install required dev dependencies

build:  ## build release
	cargo build --release --all-features

.PHONY: lint lints fix format
lint:  ## run Clippy for linting, rustfmt for autoformat checks
	cargo clippy --all-features
	cargo fmt --all -- --check
# alias
lints: lint

fix:  ## fix code with rustfmt
	cargo fmt --all
#alias
format: fix

.PHONY: check checks
check:
	cargo check --all-features
# alias
checks: check

.PHONY: test tests test-ci tests-ci
test:  ## run the tests
	cargo llvm-cov nextest --cobertura --output-path  junit.xml

# alias
tests: test

coverage:
	cargo llvm-cov nextest --lcov --output-path coverage

.PHONY: dist publish
dist:  ## create dist
	cargo publish --dry-run --allow-dirty

publish:  ## publish to cargo
	cargo publish

# Thanks to Francoise at marmelab.com for this
.DEFAULT_GOAL := help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

print-%:
	@echo '$*=$($*)'
