name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        template:
          - python
          - cpp
          - js
          - jupyter
          - rust
          - rustjswasm
          - cppjswasm
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Prework
      run: |
        # python
        touch pyproject.toml

        # node
        echo '{"name": "a", "version": "0.0.0", "scripts": {}}' > package.json
        printf 'lockfileVersion: '9.0'\nsettings:\n\tautoInstallPeers: true\n\texcludeLinksFromLockfile: false\nimporters:\n.: {}' > pnpm-lock.yaml

        # rust
        printf '[package]\nname = "rust"\nversion = "0.1.0"\nedition = "2021"\n[dependencies]\n' > Cargo.toml
        mkdir -p src
        printf 'fn main() {\n    println!("Hello, world!");\n}\n' > src/main.rs

    - uses: actions-ext/python/setup@14e52561e5f255ba52d2e04d3cc2f3dedb1065af
      with:
        version: '3.11'

    - run: uv pip install copier

    - name: Install clang-format
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get install -y clang-format-14
          sudo ln -sf /usr/bin/clang-format-14 /usr/bin/clang-format
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install clang-format
        fi
      if: matrix.template == 'cpp' || matrix.template == 'cppjswasm'

    - uses: actions-ext/node/setup@3478453a763ed3c8c6eba05a092ab81a265c5492
      with:
        version: 22.x
        pnpm_version: 11.11.0
        js_folder: "."
      if: matrix.template == 'js' || matrix.template == 'jupyter' || matrix.template == 'cppjswasm' || matrix.template == 'rustjswasm'

    - uses: actions-ext/rust/setup@c9cdbe5cc8a2485bf2eb22644302559c741ca763
      if: matrix.template == 'rust' || matrix.template == 'rustjswasm'

    - run: pnpm install
      if: matrix.template == 'js' || matrix.template == 'jupyter' || matrix.template == 'cppjswasm' || matrix.template == 'rustjswasm'

    - run: cargo build
      if: matrix.template == 'rust' || matrix.template == 'rustjswasm'

    - run: |
        make gen-${{matrix.template}}
        make test-${{matrix.template}}
