name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        template:
          - python
          # - cpp
          - js
          - jupyter
          - rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-ext/python/setup@main
      with:
        version: '3.11'

    - run: pip install copier

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - run: |
        make gen-${{matrix.template}}
        make test-${{matrix.template}}
